name: competitivecodingarena
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  easy_pie_chart: ^1.0.0
  calendar_date_picker2: ^1.1.5
  faker: ^2.1.0
  font_awesome_flutter: ^10.7.0
  flutter_native_splash: ^2.4.1
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  firebase_analytics: ^11.4.1
  http: ^1.2.2
  flutter_code_editor: ^0.3.2
  google_sign_in_web: ^0.12.4+2
  flutter_web_auth: ^0.6.0
  flutter_riverpod: ^2.5.1
  agora_rtc_engine: ^6.3.2
  permission_handler: ^11.3.1
  audioplayers: ^6.0.0
  segmented_button_slide: ^2.0.0
  uuid: ^4.4.2
  fl_chart: ^0.70.2
  flutter_syntax_view: ^4.1.0
  dev_icons: ^1.0.0
  razorpay_web: ^1.4.2
  firebase_messaging: ^15.2.1
  google_generative_ai: ^0.4.6
  intl: ^0.19.0
  firebase_admin_sdk: ^0.0.4
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  web: ^1.1.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^3.0.2  
  geolocator: ^13.0.2
  flutter_map_location_marker: ^9.1.1
  highlight: any
  flutter_highlight: any
  url_launcher: ^6.3.1
  geocode: ^1.0.3
  shared_preferences: ^2.5.2
  cached_network_image: ^3.4.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  firebase_auth_web: ^5.8.13

flutter:
  uses-material-design: true

  assets:
  - assets/images/bg.png
  - assets/images/data.png
  - assets/images/course.png
  - assets/images/logo.png
  - assets/images/verification.png
  - assets/images/userpng.png
  - assets/images/list.png
  - assets/images/progress.png
  - assets/images/trophy.png
  - assets/images/settings.png
  - assets/images/help.png 
  - assets/images/amazonSpring.png 
  - assets/images/javascript30.png 
  - assets/images/leetcode75.png 
  - assets/images/pandas.png 
  - assets/images/sql50.png 
  - assets/images/top150.png 
  - assets/sounds/mp.mp3
  
flutter_native_splash:
  color: "#000000"
  image: assets/images/logo.png
