// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRwKFSOwufzarx7wOAiTb485273bFNmMg',
    appId: '1:702832973350:web:20d095a1a2f61a28b478e7',
    messagingSenderId: '702832973350',
    projectId: 'leetcode-94c79',
    authDomain: 'leetcode-94c79.firebaseapp.com',
    storageBucket: 'leetcode-94c79.appspot.com',
    measurementId: 'G-02DBXD6D3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmmXnES9U1yNB8a_HdR_7XBcbmAzEQx1s',
    appId: '1:702832973350:android:6c2799d2daef1d23b478e7',
    messagingSenderId: '702832973350',
    projectId: 'leetcode-94c79',
    storageBucket: 'leetcode-94c79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpnU_5sW4Yzhg05sQvJJ5n-IKLfaEPP_0',
    appId: '1:702832973350:ios:6119e09b5fa1ad44b478e7',
    messagingSenderId: '702832973350',
    projectId: 'leetcode-94c79',
    storageBucket: 'leetcode-94c79.appspot.com',
    iosClientId: '702832973350-0s560ph506hudvdrh5ufn7s34l47kcqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.leetcodeclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpnU_5sW4Yzhg05sQvJJ5n-IKLfaEPP_0',
    appId: '1:702832973350:ios:bbc0cab6b12853d6b478e7',
    messagingSenderId: '702832973350',
    projectId: 'leetcode-94c79',
    storageBucket: 'leetcode-94c79.appspot.com',
    iosClientId: '702832973350-utup3sc9i56g4nme7kdkh804gsc0meot.apps.googleusercontent.com',
    iosBundleId: 'com.example.leetcodeclone.RunnerTests',
  );
}
